# 任务分配问题（匈牙利算法）
    https://blog.csdn.net/qq_25945437/article/details/70835157
    问题描述：N个人分配N项任务，一个人只能分配一项任务，一项任务只能分配给一个人，将一项任务分配给一个人是需要支付报酬，如何分配任务，保证支付的报酬总数最小。
    范例(成本矩阵)：
$\begin{array}{c|c}
        & work1 & work2 & work3 \\
\hline
person1 & 250   & 400   & 350   \\
\hline
person1 & 400   & 600   & 350   \\
\hline
person1 & 200   & 400   & 250   \\
\end{array}$


# linear_assignment
    from sklearn.utils.linear_assignment_ import linear_assignment
    

In [1]:
from sklearn.utils.linear_assignment_ import linear_assignment
import numpy as np

#成本矩阵
cost=np.array([[90, 75, 75, 80],
               [35, 85, 55, 65],
               [125,95, 90, 105],
               [45, 110, 95, 115]],dtype=np.float32)
#指派结果
matched_indices = linear_assignment(cost)
print('cost matrix:')
print(cost)
print('matched_indices[first column is person,second column is work]:')
print(matched_indices)

cost matrix:
[[ 90.  75.  75.  80.]
 [ 35.  85.  55.  65.]
 [125.  95.  90. 105.]
 [ 45. 110.  95. 115.]]
matched_indices[first column is person,second column is work]:
[[0 3]
 [1 2]
 [2 1]
 [3 0]]
