# TensorFlow 1.10.1版本测试范例
    张量 Tensor("Const_7:0", shape=(), dtype=int32) ，Const_7为节点名，0为输出序号
* 判断变量是否存在
* 打印所有变量
* 获取模型所有可训练参数总量
* Graph
* Session
* Tensorboard
* constant
* Variable
* get_variable
* 变量共享
* 变量赋值
* placeholder
* K.shape 获取张量shape

# 判断变量是否存在

In [36]:
import tensorflow as tf

def is_exist_var(var_name):
    for v in tf.global_variables():
        if(v.name==var_name):
            return True
    return False

tf.reset_default_graph()
c1=tf.constant(1,name='c1')
v1=tf.Variable(initial_value=tf.random_normal(()),name='v1')
print(is_exist_var('v2:0'))
if not is_exist_var('v2:0'):
    v2=tf.get_variable(name='v2',shape=(1,))

for v in tf.global_variables():
    print(v.name)

False
v1:0
v2:0


# 打印所有变量

In [24]:
import tensorflow as tf

#打印所有可训练的变量
def print_all_trainable_vars():
    for v in tf.trainable_variables():
        print(v)    
        
#打印所有变量
def print_all_vars():
    for v in tf.global_variables():
        print(v)
        
sess=tf.InteractiveSession()
tf.reset_default_graph()
v1=tf.get_variable('v1',shape=(1,))
v2=tf.get_variable('v2',shape=(2,))

print_all_trainable_vars()
print_all_vars()

sess.close()

<tf.Variable 'v1:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'v2:0' shape=(2,) dtype=float32_ref>
<tf.Variable 'v1:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'v2:0' shape=(2,) dtype=float32_ref>


# 获取模型所有可训练参数总量

In [35]:
#tensorflow 获取模型所有参数总和数量
from functools import reduce
from operator import mul

def get_num_params():
    num_params = 0
    for variable in tf.trainable_variables():
        shape = variable.get_shape()
        num_params += reduce(mul, [dim.value for dim in shape], 1)
    return num_params

tf.reset_default_graph()
v1=tf.get_variable(name='v1',shape=(2,3))
v2=tf.get_variable(name='v2',shape=(3,5))
print(get_num_params())

21


# Graph

In [8]:
import tensorflow as tf #创建默认计算图

g=tf.get_default_graph()   #获取默认计算图，import tensorflow 即创建默认计算图
s=tf.get_default_session() #获取默认会话，此时会话session初始化为None
print(g)
print(s)

sess=tf.InteractiveSession() #创建并设置为默认会话

#默认计算图
a=tf.constant(1)
b=tf.constant(2)
c=a+b
print(c)

#新建计算图
g1=tf.Graph()
g1.as_default()  #设置为默认计算图
a=tf.constant(3) #
b=tf.constant(4) #
c=a+b
tf.global_variables_initializer().run() #初始化所有变量
print(c.eval())                         #图计算
print(sess.run(c))                      #图计算

#创建会话并设置计算图
with tf.Session(graph=g1) as sess:
    a=tf.constant(5)
    b=tf.constant(6)
    c=a+b
    tf.global_variables_initializer().run() #初始化所有变量
    print(c.eval())                         #图计算
    print(sess.run(c))                      #图计算


Tensor("add_2:0", shape=(), dtype=int32)
7
7
11
11


/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


# Session

In [18]:
import tensorflow as tf
sess=tf.InteractiveSession()

a=tf.constant(1)
b=tf.constant(2)
c=a+b
tf.global_variables_initializer().run()
print(c.eval())
print(sess.run(c))

3
3


# Tensorboard

In [ ]:
import tensorflow as tf

# Constant
    tf.constant(
        value,               #常量值
        dtype=None,          #常量类型
        shape=None,
        name='Const',
        verify_shape=False
    )

    常量不可以修改

In [7]:
import tensorflow as tf
import numpy as np
sess=tf.InteractiveSession()  #执行变量值，必须创建session
#标量定义
v1=tf.constant(1)             #定义常量
v1_share=v1
print('type(v1):',type(v1))   #类型：<class 'tensorflow.python.framework.ops.Tensor'>
print('v1:',v1)               #对象:Tensor("Const_1:0", shape=(), dtype=int32)
print('v1.eval():',v1.eval()) #1
print('v1 is v1_share:',v1 is v1_share)   #v1,v1_share共享对象，是同一个常量

#数组定义
v2=tf.constant([[1,2],[3,4]])
print('v2.eval():\n',v2.eval())

sess.close()
#tf.constant是否可以修改？不可以

type(v1): <class 'tensorflow.python.framework.ops.Tensor'>
v1: Tensor("Const_7:0", shape=(), dtype=int32)
v1.eval(): 1
v1 is v1_share: True
v2.eval():
 [[1 2]
 [3 4]]


# Variable
    每次调用都新建一个变量
    tf.Variable:
    __init__(
        initial_value=None,   #初始值
        trainable=True,       #是否可训练
        collections=None,     #属于那个集合
        validate_shape=True,
        caching_device=None,
        name=None,            #变量名称
        variable_def=None,
        dtype=None,           #数据类型
        expected_shape=None,
        import_scope=None,
        constraint=None
    )
    
    Properties
        device
            The name of the device on which this tensor will be produced, or None.
        dtype
            The DType of elements in this tensor.
        graph
            The Graph that contains this tensor.
        name
            The string name of this tensor.
        op
            The Operation that produces this tensor as an output.
        shape
            Returns the TensorShape that represents the shape of this tensor.    

In [10]:
import tensorflow as tf
import numpy as np

sess=tf.InteractiveSession()
v=tf.Variable(initial_value=tf.random_normal((2,3),mean=0.0,stddev=1.0),name='v')

#初始化单个变量
#sess.run(v.initializer) 
#初始化所有变量
init = tf.global_variables_initializer()
sess.run(init)

print('v:',v)
print('v.eval():',v.eval())
print('--------------------')
print('v.device:',v.device)
print('v.dtype:',v.dtype)
print('v.graph:',v.graph)
print('v.name:',v.name)
print('v.op:',v.op)
print('v.shape:',v.shape)
        


v: <tf.Variable 'v_2:0' shape=(2, 3) dtype=float32_ref>
v.eval(): [[ 0.43273774 -0.76179725  1.1159071 ]
 [-0.17345443 -1.2333782   1.4139394 ]]
--------------------
v.device: 
v.dtype: <dtype: 'float32_ref'>
v.graph: <tensorflow.python.framework.ops.Graph object at 0x7fc475d22eb8>
v.name: v_2:0
v.op: name: "v_2"
op: "VariableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 2
      }
      dim {
        size: 3
      }
    }
  }
}
attr {
  key: "shared_name"
  value {
    s: ""
  }
}

v.shape: (2, 3)


## tf.get_variable
    变量:如果变量已存在，将触发异常；可以提供共享变量机制。
    tf.get_variable(
        name,
        shape=None,
        dtype=None,
        initializer=None,
        regularizer=None,
        trainable=None,
        collections=None,
        caching_device=None,
        partitioner=None,
        validate_shape=True,
        use_resource=None,
        custom_getter=None,
        constraint=None,
        synchronization=tf.VariableSynchronization.AUTO,
        aggregation=tf.VariableAggregation.NONE
    )

In [22]:
import tensorflow as tf
import numpy as np

sess=tf.InteractiveSession()

tf.reset_default_graph()
v1=tf.get_variable(name='v1',shape=(1,))
print(v1)

<tf.Variable 'v1:0' shape=(1,) dtype=float32_ref>


# 变量共享
    tf.Variable 与 tf.get_variable的区别

    使用tf.Variable时，如果检测到命名冲突，系统会自己处理。使用tf.get_variable()时，系统不会处理冲突，而会报错;
    tf.Variable每次都会创建一个新变量,tf.get_variable一个已存在的变量时会触发异常;
    tf.get_variable可以与tf.variable_scope配合使用共享变量

In [38]:
import tensorflow as tf
import numpy as np

sess=tf.InteractiveSession()                                    #创建会话
tf.reset_default_graph()                                        #重置图:清空所有节点变量
#-----变量共享-----
#定义变量
with tf.variable_scope('scope1'):
    v3=tf.get_variable(name='v3',shape=(1,))     #定义变量
    v4=tf.get_variable(name='v4',shape=(2,))     #定义变量
#变量共享,reuse=True
with tf.variable_scope("scope1",reuse=True):
    v3=tf.get_variable("v3", shape=(1,))         #共享变量
    v4=tf.get_variable("v4", shape=(2,))         #共享变量

print_all_trainable_vars()    #输出所有可训练变量
print_all_vars()              #输出所有变量

sess.close()

<tf.Variable 'v1:0' shape=(2, 2) dtype=float32_ref>
<tf.Variable 'v2:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'scope1/v3:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'scope1/v4:0' shape=(2,) dtype=float32_ref>
<tf.Variable 'v1:0' shape=(2, 2) dtype=float32_ref>
<tf.Variable 'v2:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'scope1/v3:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'scope1/v4:0' shape=(2,) dtype=float32_ref>


# 变量赋值

In [42]:
import tensorflow as tf
tf.reset_default_graph()
sess=tf.InteractiveSession()

var=tf.Variable(np.random.rand(2,3),dtype=tf.float32)
var.initializer.run()
sess.run(tf.assign(var,[[1.,2.,3.],[4.,5.,6.]]))
print(var.eval())

[[1. 2. 3.]
 [4. 5. 6.]]


# placeholder
x=tf.placeholder(tf.float32, shape=(None,2,3), name=None)
*    dtype：表示tensorflow中的数据类型，如常用的tf.float32,tf.float64等数值类型;
*    shape：表示数据类型，默认的None是一个一维的数值，shape=[None,5],表示行不定，列是5;
*    name：张量名称;

In [39]:
import tensorflow as tf
tf.reset_default_graph()

input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
 
output = tf.multiply(input1, input2)

with tf.Session() as sess:
    print(sess.run(input1,feed_dict={input1:[3.]}))
    print(sess.run(input2,feed_dict={input2:[4.]}))
    print(sess.run(output, feed_dict = {input1:[3.], input2: [4.]}))

[3.]
[4.]
[12.]


## K.shape 获取张量shape,返回也是张量(一维张量)

In [7]:
import tensorflow as tf
import keras.backend as K

tf.reset_default_graph()
sess=tf.InteractiveSession()
c1=tf.constant([[[1,2],[4,5]],[[1,2],[4,5]]])
v=K.shape(c1) #返回张量c1的shape
tf.global_variables_initializer().run()
print(v)
print(v.eval())

Tensor("Shape:0", shape=(3,), dtype=int32)
[2 2 2]


## K.tile(x,n) 
    将x在各个维度上重复n次，x为张量，n为与x维度数目相同的列表

In [13]:
import tensorflow as tf
import keras.backend as K

tf.reset_default_graph()
sess=tf.InteractiveSession()

c1=tf.constant([[1,2,3],[4,5,6]])
t1=K.tile(c1,[1,1]) #没有重复，相当于不变
t2=K.tile(c1,[2,1]) #第一维方向重复2次
t3=K.tile(c1,[1,2]) #第二维方向重复2次
t4=K.tile(c1,[2,2]) #第1维，第2维方向各重复2次
print(c1)
print(t1)
print(t2)
print(t3)
print(t4)

Tensor("Const:0", shape=(2, 3), dtype=int32)
Tensor("Tile:0", shape=(2, 3), dtype=int32)
Tensor("Tile_1:0", shape=(4, 3), dtype=int32)
Tensor("Tile_2:0", shape=(2, 6), dtype=int32)
Tensor("Tile_3:0", shape=(4, 6), dtype=int32)
