# numpy基本操作范例
* 构造数组
* 获取数组属性
* 类型判断
* 类型转换
* 添加/删除/修改
* 数组拷贝
* arange
* 索引与切片
* reshape
* 布尔索引
* np.where条件查询
* 数组文件输入输出
* 数组合并
* 随机数
* 打乱顺序和随机抽取
* 分布函数
* 基本矩阵运算
* 矩阵分解

## 构造数组

In [78]:
#构造数组
import numpy as np

#空数组
arr0=np.zeros((0,3),dtype=np.float)
print(arr0)
print('--------------')
#一维向量
arr1=np.array([1,2,3],dtype=np.float)
print(arr1)
print('--------------')
#二维数组
arr2=np.array([[1,2],[3,4]],dtype=np.float)
print(arr2)
print('--------------')
#zeros
arr3=np.zeros((2,3),dtype=np.float)
print(arr3)
print('--------------')
#ones
arr4=np.ones((2,3),dtype=np.float)
print(arr4)
print('--------------')
#字符串数组:unicode
arr5=np.array([['你好a00','a01'],['a10','a11']])
print(arr5)
print('arr5.dtype:',arr5.dtype)
#字符串数组:byte
arr6=np.array([['a00','a01'],['a10','111']],dtype=np.string_)
print(arr6)
print('arr6.dtype:',arr6.dtype)

[]
[1. 2. 3.]
--------------
[[1. 2.]
 [3. 4.]]
--------------
[[0. 0. 0.]
 [0. 0. 0.]]
--------------
[[1. 1. 1.]
 [1. 1. 1.]]
--------------
[['你好a00' 'a01']
 ['a10' 'a11']]
arr5.dtype: <U5
[[b'a00' b'a01']
 [b'a10' b'111']]
arr6.dtype: |S3


## 获取数组属性

In [59]:
import numpy as np

arr=np.array([1,2])
print(a.ndim)      #数组的维数  
print(a.shape)     #数组每一维的大小  
print(a.size)      #数组的元素数  
print(a.dtype)     #元素类型  >";
print(a.itemsize)  #每个元素所占的字节数  

2
(2, 2)
4
int64
8


## 类型判断

In [3]:
import numpy as np

a1=1
print(type(a1))
np.issubdtype(type(a1),np.int)

<class 'int'>


/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:5: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  """


True

## 类型转换

In [21]:
#类型转换
import numpy as np

arr1=np.array([1,2],dtype=np.int)
arr2=arr1.astype(np.float)       #类型转换

print('arr1:',arr1)
print('arr1.dtype:',arr1.dtype)
print('arr2:',arr2)
print('arr2.dtype:',arr2.dtype)

arr1: [1 2]
arr1.dtype: int64
arr2: [1. 2.]
arr2.dtype: float64


## 添加/删除/修改
    3.2.9 Adding and removing elements
    delete(arr, obj[, axis])
    insert(arr, obj, values[, axis])
    append(arr, values[, axis])
    resize(a, new_shape)
    trim_zeros(filt[, trim])
    unique(ar[, return_index, return_inverse])

In [30]:
#添加/删除/修改
import numpy as np

#构造数组
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
obj=0
axis=0
#添加一行/列
arr1=np.insert(arr,obj=obj,values=[0,0,0],axis=axis) #在第obj行插入，原数组内容不变,axis=0=>插入行,axis=1=>插入列
print(arr1)
#删除一行/列
arr2=np.insert(arr,obj=obj,values=[0,0,0],axis=axis) #删除第obj行，原数组内容不变,axis=0=>删除行,axis=1=>删除列
#修改元素
arr[0,0]=10

print(arr)
print(arr1)
print(arr2)
print(arr)

[[0 0 0]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[0 0 0]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## 数组拷贝

In [63]:
import numpy as np

#数组对象自带了浅拷贝和深拷贝的方法，但是一般用深拷贝多一些：
a = np.ones((2,2))  
b = a         #浅拷贝  
print(b is a) 
#True  
c = a.copy()  #深拷贝  
print(c is a) 
#False

True
False


## arange

In [32]:
import numpy as np

arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## 索引与切片

In [44]:
import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr1=arr[0,0]
arr2=arr[:]
arr3=arr[0:2,:]
arr4=arr[:,0:2]
arr5=arr[:,-1]
arr6=arr[0:3:2,:]         #start:end:strides => 0->3,strides=2
arr7=arr[[0,1,2],[0,1,2]]
print('--------arr----------')
print(arr)
print('--------arr1----------')
print(arr1)
print('--------arr2----------')
print(arr2)
print('--------arr3----------')
print(arr3)
print('--------arr4----------')
print(arr4)
print('--------arr5----------')
print(arr5)
print('--------arr6----------')
print(arr6)
print('--------arr7----------')
print(arr7)

--------arr----------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------arr1----------
1
--------arr2----------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------arr3----------
[[1 2 3 4]
 [5 6 7 8]]
--------arr4----------
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
--------arr5----------
[ 4  8 12 16]
--------arr6----------
[[ 1  2  3  4]
 [ 9 10 11 12]]
--------arr7----------
[ 1  6 11]


## reshape

In [45]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
arr1=arr.reshape(3,2)
print(arr)
print(arr1)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


## 布尔索引

In [55]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1=arr>1          #返回布尔矩阵
arr2=arr[arr1]      #结果为一维数组   
print(arr)
print(arr1)
print(arr[arr1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [ True  True  True]
 [ True  True  True]]
[4 5 6 7 8 9]


## np.where条件查询

In [6]:
import numpy as np
#构造随机数据
x=np.random.rand(10,1)
print('x:')
print(x)
#大于0.5的设置为0,否则为1
y=np.where(x<0.5,0,1)
print('y(1):')
print(y)
#返回大于0.3小于0.7的索引:索引坐标，第一个数组为第一维，第二个数组为第二维，以此类推
y_index=np.where((x>0.3)&(x<0.7))
print('y_index:')
print(y_index)
print(x[y_index[0]])

x:
[[0.1528774 ]
 [0.39498801]
 [0.1751419 ]
 [0.08491202]
 [0.08148153]
 [0.18896528]
 [0.70298597]
 [0.2856241 ]
 [0.71245097]
 [0.79321483]]
y(1):
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]]
y_index:
(array([1]), array([0]))
[[0.39498801]]


## 数组文件输入输出

In [58]:
import os
import numpy as np

data_file1='%s/work/data/gtest/arr.npy'%os.getenv('HOME')
data_file2='%s/work/data/gtest/arr.txt'%os.getenv('HOME')

arr=np.array([[1,2,3],[4,5,6]])
#保存到文件
np.save(data_file1,arr)
np.savetxt(data_file2,arr)
#从文件加载
arr1=np.load(data_file1)
arr2=np.loadtxt(data_file2)

print(arr)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


## 数组合并

In [62]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr3=np.vstack((arr1,arr2)) #垂直方向合并
arr4=np.hstack((arr1,arr2)) #水平方向合并

print(arr1)
print(arr2)
print(arr3)
print(arr4)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## 随机数

In [72]:
import numpy as np

arr1=np.random.randint(0,10,size=(2,3)) #随机整数
arr2=np.random.rand(2,3)                #产生[0,1]均匀分布随机数
arr3=np.random.randn(2,3)               #产生正态分布随机数

print(arr1)
print(arr2)
print(arr3)

[[2 5 9]
 [5 6 8]]
[[0.57 0.84 0.81]
 [0.21 0.77 0.19]]


## 打乱顺序和随机抽取

In [9]:
import numpy as np

arr=np.arange(10) 
arr1=np.random.permutation(10) #随机生成一个乱序数组:参数为n，返回[0,n)的乱序
arr2=np.random.permutation(arr)#随机生成一个乱序数组:参数为narray，返回随机打乱的数组
arr3=arr.copy()                #硬拷贝
np.random.shuffle(arr3)        #直接将原数组打乱
arr4=np.random.choice(arr,size=(2,2),replace=True)#从样本随机抽取,size为输出数组大小，replace是否可重复抽取
arr5=np.random.choice(10,3,replace=True)#从0-10的数中随机抽取,3为输出数组大小，replace是否可重复抽取

print('-------arr-------')
print(arr)
print('-------arr1-------')
print(arr1)
print('-------arr2-------')
print(arr2)
print('-------arr3-------')
print(arr3)
print('-------arr4-------')
print(arr4)
print('-------arr5-------')
print(arr5)

-------arr-------
[0 1 2 3 4 5 6 7 8 9]
-------arr1-------
[3 7 4 8 1 2 5 9 6 0]
-------arr2-------
[9 7 0 6 5 2 1 4 3 8]
-------arr3-------
[3 4 8 1 6 9 7 2 0 5]
-------arr4-------
[[9 6]
 [6 4]]
-------arr5-------
[1 8 7]


## 分布函数

In [3]:
import numpy as np

r1 = np.random.normal(100,10,size = (3,4)) #正太分布 #第一个参数是均值，第二个参数是标准差
r2 = np.random.uniform(0,10,size = (3,4))  #均匀分布 #前两个参数分别是区间的初始值和终值
r3 = np.random.poisson(2.0,size = (3,4))   #泊松分布 #第一个参数为指定的lanbda系数

print(r1)
print(r2)
print(r3)

[[104.79400617 100.28574284  93.17195599 104.36777244]
 [ 93.51572539  99.307251   100.91353044 119.51079443]
 [ 89.71499082 102.22749685  99.06256394 103.53725919]]
[[1.39708815 4.77200709 1.23430095 6.33495786]
 [4.72090179 5.71883352 0.67857823 5.46761093]
 [9.44187031 0.88100464 0.18090888 1.97106212]]
[[1 2 1 3]
 [3 2 2 5]
 [3 4 2 0]]


## 基本的矩阵运算

In [64]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
arr1=arr.transpose()  #转置

#numpy.linalg模块中有很多关于矩阵运算的方法：
#特征值、特征向量：
a = np.array([[1,0],[2,3]])  
print(nplg.eig(a)) 
#(array([ 3.,  1.]), array([[ 0.        ,  0.70710678],  
#       [ 1.        , -0.70710678]]))


(array([3., 1.]), array([[ 0.  ,  0.71],
       [ 1.  , -0.71]]))


## 矩阵分解

In [ ]:
import numpy as np
